// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXfOvXcvzDmHZGjxoE2_ABsBPGlmTf0-w',
    appId: '1:895926008499:web:1263e4d35b712c76ff8ec6',
    messagingSenderId: '895926008499',
    projectId: 'asnan-hub',
    authDomain: 'asnan-hub.firebaseapp.com',
    storageBucket: 'asnan-hub.firebasestorage.app',
    measurementId: 'G-7KG505EJ3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSW4NbqDXmCO31VzHzOc3OUH2h3m4uvXA',
    appId: '1:895926008499:android:06e11cac3a1e6b76ff8ec6',
    messagingSenderId: '895926008499',
    projectId: 'asnan-hub',
    storageBucket: 'asnan-hub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxILOqR-cnykOj8EQxmB3mHDbt2YZfhME',
    appId: '1:895926008499:ios:595eb57bca235068ff8ec6',
    messagingSenderId: '895926008499',
    projectId: 'asnan-hub',
    storageBucket: 'asnan-hub.firebasestorage.app',
    iosBundleId: 'com.example.asnanHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxILOqR-cnykOj8EQxmB3mHDbt2YZfhME',
    appId: '1:895926008499:ios:595eb57bca235068ff8ec6',
    messagingSenderId: '895926008499',
    projectId: 'asnan-hub',
    storageBucket: 'asnan-hub.firebasestorage.app',
    iosBundleId: 'com.example.asnanHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXfOvXcvzDmHZGjxoE2_ABsBPGlmTf0-w',
    appId: '1:895926008499:web:64a76ef877db9bcfff8ec6',
    messagingSenderId: '895926008499',
    projectId: 'asnan-hub',
    authDomain: 'asnan-hub.firebaseapp.com',
    storageBucket: 'asnan-hub.firebasestorage.app',
    measurementId: 'G-46J6SP65XS',
  );

}